version: '3.4'

networks:
  blast-cluster:
    driver: bridge

services:
  manager1:
    container_name: manager1
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2110:2110
      - 5110:5110
      - 6110:6110
      - 8110:8110
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    command: >
      blast manager start
      --node-id=blast-manager1
      --node-address=manager1:2110
      --grpc-address=manager1:5110
      --grpc-gateway-address=manager1:6110
      --http-address=manager1:8110
      --data-dir=/tmp/blast/manager1
      --raft-storage-type=boltdb
      --index-mapping-file=/opt/blast/example/wiki_index_mapping.json
      --index-type=scorch
      --index-storage-type=scorch

  indexer1:
    container_name: indexer1
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2010:2010
      - 5010:5010
      - 6010:6010
      - 8010:8010
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard1
      --node-id=blast-indexer1
      --node-address=indexer1:2010
      --grpc-address=indexer1:5010
      --grpc-gateway-address=indexer1:6010
      --http-address=indexer1:8010
      --data-dir=/tmp/blast/indexer1
      --raft-storage-type=boltdb

  indexer2:
    container_name: indexer2
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2020:2020
      - 5020:5020
      - 6020:6020
      - 8020:8020
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard1
      --node-id=blast-indexer2
      --node-address=indexer2:2020
      --grpc-address=indexer2:5020
      --grpc-gateway-address=indexer2:6020
      --http-address=indexer2:8020
      --data-dir=/tmp/blast/indexer2
      --raft-storage-type=boltdb

  indexer3:
    container_name: indexer3
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2030:2030
      - 5030:5030
      - 6030:6030
      - 8030:8030
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard1
      --node-id=blast-indexer3
      --node-address=indexer3:2030
      --grpc-address=indexer3:5030
      --grpc-gateway-address=indexer3:6030
      --http-address=indexer3:8030
      --data-dir=/tmp/blast/indexer3
      --raft-storage-type=boltdb

  indexer4:
    container_name: indexer4
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2040:2040
      - 5040:5040
      - 6040:6040
      - 8040:8040
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard2
      --node-id=blast-indexer4
      --node-address=indexer4:2040
      --grpc-address=indexer4:5040
      --grpc-gateway-address=indexer4:6040
      --http-address=indexer4:8040
      --data-dir=/tmp/blast/indexer4
      --raft-storage-type=boltdb

  indexer5:
    container_name: indexer5
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2050:2050
      - 5050:5050
      - 6050:6050
      - 8050:8050
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard2
      --node-id=blast-indexer5
      --node-address=indexer5:2050
      --grpc-address=indexer5:5050
      --grpc-gateway-address=indexer5:6050
      --http-address=indexer5:8050
      --data-dir=/tmp/blast/indexer5
      --raft-storage-type=boltdb

  indexer6:
    container_name: indexer6
    image: mosuka/blast:latest
    restart: always
    ports:
      - 2060:2060
      - 5060:5060
      - 6060:6060
      - 8060:8060
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
    command: >
      blast indexer start
      --manager-grpc-address=manager1:5110
      --shard-id=shard2
      --node-id=blast-indexer6
      --node-address=indexer6:2060
      --grpc-address=indexer6:5060
      --grpc-gateway-address=indexer6:6060
      --http-address=indexer6:8060
      --data-dir=/tmp/blast/indexer6
      --raft-storage-type=boltdb

  dispatcher1:
    container_name: dispatcher1
    image: mosuka/blast:latest
    restart: always
    ports:
      - 5210:5210
      - 6210:6210
      - 8210:8210
    networks:
      - blast-cluster
    volumes:
      - ./example:/opt/blast/example
    depends_on:
      - manager1
      - indexer1
      - indexer2
      - indexer3
      - indexer4
      - indexer5
      - indexer6
    command: >
      blast dispatcher start
      --manager-grpc-address=manager1:5110
      --grpc-address=dispatcher1:5210
      --grpc-gateway-address=dispatcher1:6210
      --http-address=dispatcher1:8210
