// Code generated by protoc-gen-go.
// source: proto/index_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/index_service.proto

It has these top-level messages:
	GetIndexInfoRequest
	GetIndexInfoResponse
	PutDocumentRequest
	PutDocumentResponse
	GetDocumentRequest
	GetDocumentResponse
	DeleteDocumentRequest
	DeleteDocumentResponse
	BulkRequest
	BulkResponse
	SearchRequest
	SearchResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetIndexInfoRequest struct {
	IndexPath    bool `protobuf:"varint,1,opt,name=index_path,json=indexPath" json:"index_path,omitempty"`
	IndexMapping bool `protobuf:"varint,2,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
	IndexType    bool `protobuf:"varint,3,opt,name=index_type,json=indexType" json:"index_type,omitempty"`
	Kvstore      bool `protobuf:"varint,4,opt,name=kvstore" json:"kvstore,omitempty"`
	Kvconfig     bool `protobuf:"varint,5,opt,name=kvconfig" json:"kvconfig,omitempty"`
}

func (m *GetIndexInfoRequest) Reset()                    { *m = GetIndexInfoRequest{} }
func (m *GetIndexInfoRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetIndexInfoRequest) ProtoMessage()               {}
func (*GetIndexInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetIndexInfoRequest) GetIndexPath() bool {
	if m != nil {
		return m.IndexPath
	}
	return false
}

func (m *GetIndexInfoRequest) GetIndexMapping() bool {
	if m != nil {
		return m.IndexMapping
	}
	return false
}

func (m *GetIndexInfoRequest) GetIndexType() bool {
	if m != nil {
		return m.IndexType
	}
	return false
}

func (m *GetIndexInfoRequest) GetKvstore() bool {
	if m != nil {
		return m.Kvstore
	}
	return false
}

func (m *GetIndexInfoRequest) GetKvconfig() bool {
	if m != nil {
		return m.Kvconfig
	}
	return false
}

type GetIndexInfoResponse struct {
	IndexPath    string               `protobuf:"bytes,1,opt,name=index_path,json=indexPath" json:"index_path,omitempty"`
	IndexMapping *google_protobuf.Any `protobuf:"bytes,2,opt,name=index_mapping,json=indexMapping" json:"index_mapping,omitempty"`
	IndexType    string               `protobuf:"bytes,3,opt,name=index_type,json=indexType" json:"index_type,omitempty"`
	Kvstore      string               `protobuf:"bytes,4,opt,name=kvstore" json:"kvstore,omitempty"`
	Kvconfig     *google_protobuf.Any `protobuf:"bytes,5,opt,name=kvconfig" json:"kvconfig,omitempty"`
	Succeeded    bool                 `protobuf:"varint,6,opt,name=succeeded" json:"succeeded,omitempty"`
	Message      string               `protobuf:"bytes,7,opt,name=message" json:"message,omitempty"`
}

func (m *GetIndexInfoResponse) Reset()                    { *m = GetIndexInfoResponse{} }
func (m *GetIndexInfoResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetIndexInfoResponse) ProtoMessage()               {}
func (*GetIndexInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetIndexInfoResponse) GetIndexPath() string {
	if m != nil {
		return m.IndexPath
	}
	return ""
}

func (m *GetIndexInfoResponse) GetIndexMapping() *google_protobuf.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

func (m *GetIndexInfoResponse) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *GetIndexInfoResponse) GetKvstore() string {
	if m != nil {
		return m.Kvstore
	}
	return ""
}

func (m *GetIndexInfoResponse) GetKvconfig() *google_protobuf.Any {
	if m != nil {
		return m.Kvconfig
	}
	return nil
}

func (m *GetIndexInfoResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *GetIndexInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutDocumentRequest struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *PutDocumentRequest) Reset()                    { *m = PutDocumentRequest{} }
func (m *PutDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*PutDocumentRequest) ProtoMessage()               {}
func (*PutDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentRequest) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type PutDocumentResponse struct {
	Id        string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields    *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
	Succeeded bool                 `protobuf:"varint,3,opt,name=succeeded" json:"succeeded,omitempty"`
	Message   string               `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *PutDocumentResponse) Reset()                    { *m = PutDocumentResponse{} }
func (m *PutDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*PutDocumentResponse) ProtoMessage()               {}
func (*PutDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *PutDocumentResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *PutDocumentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDocumentRequest) Reset()                    { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()               {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetDocumentResponse struct {
	Id        string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields    *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
	Succeeded bool                 `protobuf:"varint,3,opt,name=succeeded" json:"succeeded,omitempty"`
	Message   string               `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *GetDocumentResponse) Reset()                    { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()               {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetDocumentResponse) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *GetDocumentResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *GetDocumentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Succeeded bool   `protobuf:"varint,2,opt,name=succeeded" json:"succeeded,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteDocumentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteDocumentResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *DeleteDocumentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BulkRequest struct {
	BatchSize      int32                        `protobuf:"varint,1,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	UpdateRequests []*BulkRequest_UpdateRequest `protobuf:"bytes,2,rep,name=update_requests,json=updateRequests" json:"update_requests,omitempty"`
}

func (m *BulkRequest) Reset()                    { *m = BulkRequest{} }
func (m *BulkRequest) String() string            { return proto1.CompactTextString(m) }
func (*BulkRequest) ProtoMessage()               {}
func (*BulkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BulkRequest) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *BulkRequest) GetUpdateRequests() []*BulkRequest_UpdateRequest {
	if m != nil {
		return m.UpdateRequests
	}
	return nil
}

type BulkRequest_UpdateRequest struct {
	Method   string                              `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Document *BulkRequest_UpdateRequest_Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *BulkRequest_UpdateRequest) Reset()                    { *m = BulkRequest_UpdateRequest{} }
func (m *BulkRequest_UpdateRequest) String() string            { return proto1.CompactTextString(m) }
func (*BulkRequest_UpdateRequest) ProtoMessage()               {}
func (*BulkRequest_UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *BulkRequest_UpdateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *BulkRequest_UpdateRequest) GetDocument() *BulkRequest_UpdateRequest_Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type BulkRequest_UpdateRequest_Document struct {
	Id     string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fields *google_protobuf.Any `protobuf:"bytes,2,opt,name=fields" json:"fields,omitempty"`
}

func (m *BulkRequest_UpdateRequest_Document) Reset()         { *m = BulkRequest_UpdateRequest_Document{} }
func (m *BulkRequest_UpdateRequest_Document) String() string { return proto1.CompactTextString(m) }
func (*BulkRequest_UpdateRequest_Document) ProtoMessage()    {}
func (*BulkRequest_UpdateRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0, 0}
}

func (m *BulkRequest_UpdateRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BulkRequest_UpdateRequest_Document) GetFields() *google_protobuf.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type BulkResponse struct {
	PutCount      int32  `protobuf:"varint,1,opt,name=put_count,json=putCount" json:"put_count,omitempty"`
	PutErrorCount int32  `protobuf:"varint,2,opt,name=put_error_count,json=putErrorCount" json:"put_error_count,omitempty"`
	DeleteCount   int32  `protobuf:"varint,3,opt,name=delete_count,json=deleteCount" json:"delete_count,omitempty"`
	Succeeded     bool   `protobuf:"varint,4,opt,name=succeeded" json:"succeeded,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *BulkResponse) Reset()                    { *m = BulkResponse{} }
func (m *BulkResponse) String() string            { return proto1.CompactTextString(m) }
func (*BulkResponse) ProtoMessage()               {}
func (*BulkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BulkResponse) GetPutCount() int32 {
	if m != nil {
		return m.PutCount
	}
	return 0
}

func (m *BulkResponse) GetPutErrorCount() int32 {
	if m != nil {
		return m.PutErrorCount
	}
	return 0
}

func (m *BulkResponse) GetDeleteCount() int32 {
	if m != nil {
		return m.DeleteCount
	}
	return 0
}

func (m *BulkResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *BulkResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SearchRequest struct {
	SearchRequest *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest" json:"search_request,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetSearchRequest() *google_protobuf.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult *google_protobuf.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult" json:"search_result,omitempty"`
	Succeeded    bool                 `protobuf:"varint,2,opt,name=succeeded" json:"succeeded,omitempty"`
	Message      string               `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetSearchResult() *google_protobuf.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

func (m *SearchResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *SearchResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*GetIndexInfoRequest)(nil), "proto.GetIndexInfoRequest")
	proto1.RegisterType((*GetIndexInfoResponse)(nil), "proto.GetIndexInfoResponse")
	proto1.RegisterType((*PutDocumentRequest)(nil), "proto.PutDocumentRequest")
	proto1.RegisterType((*PutDocumentResponse)(nil), "proto.PutDocumentResponse")
	proto1.RegisterType((*GetDocumentRequest)(nil), "proto.GetDocumentRequest")
	proto1.RegisterType((*GetDocumentResponse)(nil), "proto.GetDocumentResponse")
	proto1.RegisterType((*DeleteDocumentRequest)(nil), "proto.DeleteDocumentRequest")
	proto1.RegisterType((*DeleteDocumentResponse)(nil), "proto.DeleteDocumentResponse")
	proto1.RegisterType((*BulkRequest)(nil), "proto.BulkRequest")
	proto1.RegisterType((*BulkRequest_UpdateRequest)(nil), "proto.BulkRequest.UpdateRequest")
	proto1.RegisterType((*BulkRequest_UpdateRequest_Document)(nil), "proto.BulkRequest.UpdateRequest.Document")
	proto1.RegisterType((*BulkResponse)(nil), "proto.BulkResponse")
	proto1.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto1.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Index service

type IndexClient interface {
	GetIndexInfo(ctx context.Context, in *GetIndexInfoRequest, opts ...grpc.CallOption) (*GetIndexInfoResponse, error)
	PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) GetIndexInfo(ctx context.Context, in *GetIndexInfoRequest, opts ...grpc.CallOption) (*GetIndexInfoResponse, error) {
	out := new(GetIndexInfoResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetIndexInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error) {
	out := new(PutDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/PutDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/GetDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := grpc.Invoke(ctx, "/proto.Index/DeleteDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	out := new(BulkResponse)
	err := grpc.Invoke(ctx, "/proto.Index/Bulk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/proto.Index/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Index service

type IndexServer interface {
	GetIndexInfo(context.Context, *GetIndexInfoRequest) (*GetIndexInfoResponse, error)
	PutDocument(context.Context, *PutDocumentRequest) (*PutDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_GetIndexInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetIndexInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexInfo(ctx, req.(*GetIndexInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/PutDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).PutDocument(ctx, req.(*PutDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/DeleteDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/Bulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexInfo",
			Handler:    _Index_GetIndexInfo_Handler,
		},
		{
			MethodName: "PutDocument",
			Handler:    _Index_PutDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _Index_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Index_DeleteDocument_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _Index_Bulk_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Index_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/index_service.proto",
}

func init() { proto1.RegisterFile("proto/index_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x7e, 0xe3, 0x7c, 0x34, 0x9e, 0x7c, 0x54, 0xda, 0x7e, 0xc8, 0x75, 0x5b, 0xa9, 0x6f, 0x40,
	0x50, 0x24, 0xe4, 0x42, 0x39, 0xa0, 0x8a, 0x13, 0xd0, 0x52, 0x22, 0x81, 0xa8, 0x52, 0x38, 0x07,
	0xd7, 0x9e, 0x24, 0x56, 0x13, 0xdb, 0x78, 0xd7, 0x15, 0xe9, 0x95, 0x23, 0x47, 0x7e, 0x00, 0xff,
	0xa0, 0x07, 0x4e, 0xfc, 0x3c, 0xe4, 0xdd, 0xb5, 0xeb, 0x6d, 0x9d, 0x44, 0xa2, 0x07, 0x4e, 0xd1,
	0x3c, 0xf3, 0xec, 0xb3, 0xf3, 0xcc, 0xac, 0x27, 0xb0, 0x11, 0x46, 0x01, 0x0b, 0xf6, 0x3c, 0xdf,
	0xc5, 0xaf, 0x7d, 0x8a, 0xd1, 0x85, 0xe7, 0xa0, 0xc5, 0x31, 0x52, 0xe5, 0x3f, 0xe6, 0xc6, 0x30,
	0x08, 0x86, 0x63, 0xdc, 0xe3, 0xd1, 0x59, 0x3c, 0xd8, 0xb3, 0xfd, 0xa9, 0x60, 0x74, 0xae, 0x4a,
	0xb0, 0x72, 0x8c, 0xac, 0x9b, 0x1c, 0xee, 0xfa, 0x83, 0xa0, 0x87, 0x5f, 0x62, 0xa4, 0x8c, 0x6c,
	0x03, 0x08, 0xc1, 0xd0, 0x66, 0x23, 0xa3, 0xb4, 0x53, 0xda, 0xad, 0xf7, 0x74, 0x8e, 0x9c, 0xd8,
	0x6c, 0x44, 0xee, 0x41, 0x4b, 0xa4, 0x27, 0x76, 0x18, 0x7a, 0xfe, 0xd0, 0xd0, 0x38, 0xa3, 0xc9,
	0xc1, 0xf7, 0x02, 0xbb, 0xd6, 0x60, 0xd3, 0x10, 0x8d, 0x72, 0x4e, 0xe3, 0xe3, 0x34, 0x44, 0x62,
	0xc0, 0xd2, 0xf9, 0x05, 0x65, 0x41, 0x84, 0x46, 0x85, 0xe7, 0xd2, 0x90, 0x98, 0x50, 0x3f, 0xbf,
	0x70, 0x02, 0x7f, 0xe0, 0x0d, 0x8d, 0x2a, 0x4f, 0x65, 0x71, 0xe7, 0x87, 0x06, 0xab, 0x6a, 0xc1,
	0x34, 0x0c, 0x7c, 0x8a, 0x05, 0x15, 0xeb, 0xf9, 0x8a, 0x0f, 0x8a, 0x2a, 0x6e, 0xec, 0xaf, 0x5a,
	0xa2, 0x37, 0x56, 0xda, 0x1b, 0xeb, 0xa5, 0x3f, 0x5d, 0xe8, 0x43, 0x9f, 0xe3, 0x43, 0xbf, 0xf6,
	0xf1, 0xe4, 0x86, 0x8f, 0x59, 0xd7, 0x65, 0x2c, 0xb2, 0x05, 0x3a, 0x8d, 0x1d, 0x07, 0xd1, 0x45,
	0xd7, 0xa8, 0x89, 0x8e, 0x65, 0x40, 0x72, 0xd3, 0x04, 0x29, 0xb5, 0x87, 0x68, 0x2c, 0x89, 0x9b,
	0x64, 0xd8, 0xe9, 0x01, 0x39, 0x89, 0xd9, 0x61, 0xe0, 0xc4, 0x13, 0xf4, 0x59, 0x3a, 0xc4, 0x36,
	0x68, 0x9e, 0x2b, 0x5b, 0xa1, 0x79, 0x2e, 0x79, 0x0c, 0xb5, 0x81, 0x87, 0x63, 0x97, 0xce, 0x35,
	0x2f, 0x39, 0x9d, 0xef, 0x25, 0x58, 0x51, 0x44, 0x65, 0xa3, 0xef, 0xa4, 0xaa, 0x3a, 0x2c, 0xcf,
	0x71, 0x58, 0x51, 0x1d, 0xde, 0x07, 0x72, 0x8c, 0x8b, 0x1c, 0xf2, 0x9a, 0x15, 0xda, 0x3f, 0xad,
	0xf9, 0x21, 0xac, 0x1d, 0xe2, 0x18, 0x19, 0x2e, 0x2a, 0xfb, 0x33, 0xac, 0xdf, 0x24, 0xce, 0x28,
	0x5c, 0x29, 0x45, 0x9b, 0x53, 0x4a, 0x59, 0x2d, 0xe5, 0x97, 0x06, 0x8d, 0x57, 0xf1, 0xf8, 0x3c,
	0xf7, 0x7d, 0x9f, 0xd9, 0xcc, 0x19, 0xf5, 0xa9, 0x77, 0x89, 0x5c, 0xbf, 0xda, 0xd3, 0x39, 0x72,
	0xea, 0x5d, 0x22, 0xe9, 0xc2, 0x72, 0x1c, 0xba, 0x36, 0xc3, 0x7e, 0x24, 0x0e, 0x24, 0x8d, 0x2a,
	0xef, 0x36, 0xf6, 0x77, 0x44, 0x87, 0xac, 0x9c, 0x96, 0xf5, 0x89, 0x33, 0x65, 0xd4, 0x6b, 0xc7,
	0xf9, 0x90, 0x9a, 0xbf, 0x4b, 0xd0, 0x52, 0x18, 0x64, 0x1d, 0x6a, 0x13, 0x64, 0xa3, 0x20, 0xf5,
	0x25, 0x23, 0x72, 0x04, 0x75, 0x57, 0xfa, 0x97, 0x63, 0x79, 0xb4, 0xe8, 0x36, 0x2b, 0x6b, 0x58,
	0x76, 0xd4, 0x7c, 0x0b, 0xf5, 0x14, 0xbd, 0xe3, 0x17, 0x70, 0x55, 0x82, 0xa6, 0xb8, 0x5a, 0x4e,
	0x63, 0x13, 0xf4, 0x30, 0x66, 0x7d, 0x27, 0x88, 0x7d, 0x26, 0x9b, 0x56, 0x0f, 0x63, 0xf6, 0x3a,
	0x89, 0xc9, 0x03, 0x58, 0x4e, 0x92, 0x18, 0x45, 0x41, 0x24, 0x29, 0x1a, 0xa7, 0xb4, 0xc2, 0x98,
	0x1d, 0x25, 0xa8, 0xe0, 0xfd, 0x0f, 0x4d, 0x97, 0x0f, 0x5b, 0x92, 0xca, 0x9c, 0xd4, 0x10, 0x98,
	0xa0, 0x28, 0x53, 0xae, 0xcc, 0x99, 0x72, 0x55, 0x9d, 0xf2, 0x3b, 0x68, 0x9d, 0xa2, 0x1d, 0x39,
	0xa3, 0xb4, 0xd5, 0x2f, 0xa0, 0x4d, 0x39, 0x90, 0xce, 0x91, 0x57, 0x3d, 0xcb, 0x77, 0x8b, 0xe6,
	0x0f, 0x77, 0xbe, 0x95, 0xa0, 0x9d, 0xca, 0xc9, 0x06, 0x1c, 0x40, 0x2b, 0xd3, 0xa3, 0xf1, 0x78,
	0xbe, 0x5c, 0x33, 0x95, 0x4b, 0x98, 0x7f, 0xfb, 0x72, 0xf7, 0x7f, 0x96, 0xa1, 0xca, 0xb7, 0x3d,
	0xe9, 0x42, 0x33, 0xbf, 0xf9, 0x89, 0x29, 0x5f, 0x47, 0xc1, 0xff, 0x97, 0xb9, 0x59, 0x98, 0x13,
	0x2e, 0x3a, 0xff, 0x91, 0x37, 0xd0, 0xc8, 0xad, 0x36, 0xb2, 0x21, 0xd9, 0xb7, 0x77, 0xa8, 0x69,
	0x16, 0xa5, 0xf2, 0x3a, 0xb9, 0x75, 0x93, 0xe9, 0xdc, 0xde, 0x54, 0xa6, 0x59, 0x94, 0xca, 0x74,
	0x3e, 0x40, 0x5b, 0x5d, 0x00, 0x64, 0x4b, 0xf2, 0x0b, 0x17, 0x88, 0xb9, 0x3d, 0x23, 0x9b, 0x09,
	0x3e, 0x85, 0x4a, 0xf2, 0x72, 0x09, 0xb9, 0xfd, 0x05, 0x99, 0x2b, 0x0a, 0x96, 0x1d, 0x79, 0x0e,
	0x35, 0x31, 0x6d, 0xb2, 0x2a, 0x09, 0xca, 0x5b, 0x32, 0xd7, 0x6e, 0xa0, 0xe9, 0xc1, 0xb3, 0x1a,
	0xc7, 0x9f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x77, 0x97, 0x0f, 0x47, 0x89, 0x08, 0x00, 0x00,
}
