// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/index/index.proto

package index

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeHealthCheckRequest_Probe int32

const (
	NodeHealthCheckRequest_UNKNOWN     NodeHealthCheckRequest_Probe = 0
	NodeHealthCheckRequest_HEALTHINESS NodeHealthCheckRequest_Probe = 1
	NodeHealthCheckRequest_LIVENESS    NodeHealthCheckRequest_Probe = 2
	NodeHealthCheckRequest_READINESS   NodeHealthCheckRequest_Probe = 3
)

var NodeHealthCheckRequest_Probe_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEALTHINESS",
	2: "LIVENESS",
	3: "READINESS",
}

var NodeHealthCheckRequest_Probe_value = map[string]int32{
	"UNKNOWN":     0,
	"HEALTHINESS": 1,
	"LIVENESS":    2,
	"READINESS":   3,
}

func (x NodeHealthCheckRequest_Probe) String() string {
	return proto.EnumName(NodeHealthCheckRequest_Probe_name, int32(x))
}

func (NodeHealthCheckRequest_Probe) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{0, 0}
}

type NodeHealthCheckResponse_State int32

const (
	NodeHealthCheckResponse_UNKNOWN   NodeHealthCheckResponse_State = 0
	NodeHealthCheckResponse_HEALTHY   NodeHealthCheckResponse_State = 1
	NodeHealthCheckResponse_UNHEALTHY NodeHealthCheckResponse_State = 2
	NodeHealthCheckResponse_ALIVE     NodeHealthCheckResponse_State = 3
	NodeHealthCheckResponse_DEAD      NodeHealthCheckResponse_State = 4
	NodeHealthCheckResponse_READY     NodeHealthCheckResponse_State = 5
	NodeHealthCheckResponse_NOT_READY NodeHealthCheckResponse_State = 6
)

var NodeHealthCheckResponse_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "HEALTHY",
	2: "UNHEALTHY",
	3: "ALIVE",
	4: "DEAD",
	5: "READY",
	6: "NOT_READY",
}

var NodeHealthCheckResponse_State_value = map[string]int32{
	"UNKNOWN":   0,
	"HEALTHY":   1,
	"UNHEALTHY": 2,
	"ALIVE":     3,
	"DEAD":      4,
	"READY":     5,
	"NOT_READY": 6,
}

func (x NodeHealthCheckResponse_State) String() string {
	return proto.EnumName(NodeHealthCheckResponse_State_name, int32(x))
}

func (NodeHealthCheckResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{1, 0}
}

type Node_State int32

const (
	Node_UNKNOWN   Node_State = 0
	Node_FOLLOWER  Node_State = 1
	Node_CANDIDATE Node_State = 2
	Node_LEADER    Node_State = 3
	Node_SHUTDOWN  Node_State = 4
)

var Node_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "FOLLOWER",
	2: "CANDIDATE",
	3: "LEADER",
	4: "SHUTDOWN",
}

var Node_State_value = map[string]int32{
	"UNKNOWN":   0,
	"FOLLOWER":  1,
	"CANDIDATE": 2,
	"LEADER":    3,
	"SHUTDOWN":  4,
}

func (x Node_State) String() string {
	return proto.EnumName(Node_State_name, int32(x))
}

func (Node_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{3, 0}
}

type ClusterWatchResponse_Event int32

const (
	ClusterWatchResponse_UNKNOWN ClusterWatchResponse_Event = 0
	ClusterWatchResponse_JOIN    ClusterWatchResponse_Event = 1
	ClusterWatchResponse_LEAVE   ClusterWatchResponse_Event = 2
	ClusterWatchResponse_UPDATE  ClusterWatchResponse_Event = 3
)

var ClusterWatchResponse_Event_name = map[int32]string{
	0: "UNKNOWN",
	1: "JOIN",
	2: "LEAVE",
	3: "UPDATE",
}

var ClusterWatchResponse_Event_value = map[string]int32{
	"UNKNOWN": 0,
	"JOIN":    1,
	"LEAVE":   2,
	"UPDATE":  3,
}

func (x ClusterWatchResponse_Event) String() string {
	return proto.EnumName(ClusterWatchResponse_Event_name, int32(x))
}

func (ClusterWatchResponse_Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{9, 0}
}

type Proposal_Event int32

const (
	Proposal_UNKNOWN     Proposal_Event = 0
	Proposal_SET_NODE    Proposal_Event = 1
	Proposal_DELETE_NODE Proposal_Event = 2
	Proposal_INDEX       Proposal_Event = 3
	Proposal_DELETE      Proposal_Event = 4
	Proposal_BULK_INDEX  Proposal_Event = 5
	Proposal_BULK_DELETE Proposal_Event = 6
)

var Proposal_Event_name = map[int32]string{
	0: "UNKNOWN",
	1: "SET_NODE",
	2: "DELETE_NODE",
	3: "INDEX",
	4: "DELETE",
	5: "BULK_INDEX",
	6: "BULK_DELETE",
}

var Proposal_Event_value = map[string]int32{
	"UNKNOWN":     0,
	"SET_NODE":    1,
	"DELETE_NODE": 2,
	"INDEX":       3,
	"DELETE":      4,
	"BULK_INDEX":  5,
	"BULK_DELETE": 6,
}

func (x Proposal_Event) String() string {
	return proto.EnumName(Proposal_Event_name, int32(x))
}

func (Proposal_Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{24, 0}
}

type NodeHealthCheckRequest struct {
	Probe                NodeHealthCheckRequest_Probe `protobuf:"varint,1,opt,name=probe,proto3,enum=index.NodeHealthCheckRequest_Probe" json:"probe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NodeHealthCheckRequest) Reset()         { *m = NodeHealthCheckRequest{} }
func (m *NodeHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*NodeHealthCheckRequest) ProtoMessage()    {}
func (*NodeHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{0}
}

func (m *NodeHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHealthCheckRequest.Unmarshal(m, b)
}
func (m *NodeHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *NodeHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHealthCheckRequest.Merge(m, src)
}
func (m *NodeHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_NodeHealthCheckRequest.Size(m)
}
func (m *NodeHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHealthCheckRequest proto.InternalMessageInfo

func (m *NodeHealthCheckRequest) GetProbe() NodeHealthCheckRequest_Probe {
	if m != nil {
		return m.Probe
	}
	return NodeHealthCheckRequest_UNKNOWN
}

type NodeHealthCheckResponse struct {
	State                NodeHealthCheckResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=index.NodeHealthCheckResponse_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NodeHealthCheckResponse) Reset()         { *m = NodeHealthCheckResponse{} }
func (m *NodeHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*NodeHealthCheckResponse) ProtoMessage()    {}
func (*NodeHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{1}
}

func (m *NodeHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHealthCheckResponse.Unmarshal(m, b)
}
func (m *NodeHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *NodeHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHealthCheckResponse.Merge(m, src)
}
func (m *NodeHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_NodeHealthCheckResponse.Size(m)
}
func (m *NodeHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHealthCheckResponse proto.InternalMessageInfo

func (m *NodeHealthCheckResponse) GetState() NodeHealthCheckResponse_State {
	if m != nil {
		return m.State
	}
	return NodeHealthCheckResponse_UNKNOWN
}

type Metadata struct {
	GrpcAddress          string   `protobuf:"bytes,1,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	GrpcGatewayAddress   string   `protobuf:"bytes,2,opt,name=grpc_gateway_address,json=grpcGatewayAddress,proto3" json:"grpc_gateway_address,omitempty"`
	HttpAddress          string   `protobuf:"bytes,3,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetGrpcAddress() string {
	if m != nil {
		return m.GrpcAddress
	}
	return ""
}

func (m *Metadata) GetGrpcGatewayAddress() string {
	if m != nil {
		return m.GrpcGatewayAddress
	}
	return ""
}

func (m *Metadata) GetHttpAddress() string {
	if m != nil {
		return m.HttpAddress
	}
	return ""
}

type Node struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BindAddress          string     `protobuf:"bytes,2,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	State                Node_State `protobuf:"varint,3,opt,name=state,proto3,enum=index.Node_State" json:"state,omitempty"`
	Metadata             *Metadata  `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{3}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetBindAddress() string {
	if m != nil {
		return m.BindAddress
	}
	return ""
}

func (m *Node) GetState() Node_State {
	if m != nil {
		return m.State
	}
	return Node_UNKNOWN
}

func (m *Node) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Cluster struct {
	Nodes                map[string]*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{4}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetNodes() map[string]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeInfoResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfoResponse) Reset()         { *m = NodeInfoResponse{} }
func (m *NodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NodeInfoResponse) ProtoMessage()    {}
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{5}
}

func (m *NodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoResponse.Unmarshal(m, b)
}
func (m *NodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoResponse.Marshal(b, m, deterministic)
}
func (m *NodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoResponse.Merge(m, src)
}
func (m *NodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NodeInfoResponse.Size(m)
}
func (m *NodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoResponse proto.InternalMessageInfo

func (m *NodeInfoResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ClusterJoinRequest struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterJoinRequest) Reset()         { *m = ClusterJoinRequest{} }
func (m *ClusterJoinRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterJoinRequest) ProtoMessage()    {}
func (*ClusterJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{6}
}

func (m *ClusterJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterJoinRequest.Unmarshal(m, b)
}
func (m *ClusterJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterJoinRequest.Marshal(b, m, deterministic)
}
func (m *ClusterJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterJoinRequest.Merge(m, src)
}
func (m *ClusterJoinRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterJoinRequest.Size(m)
}
func (m *ClusterJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterJoinRequest proto.InternalMessageInfo

func (m *ClusterJoinRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ClusterLeaveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterLeaveRequest) Reset()         { *m = ClusterLeaveRequest{} }
func (m *ClusterLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterLeaveRequest) ProtoMessage()    {}
func (*ClusterLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{7}
}

func (m *ClusterLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterLeaveRequest.Unmarshal(m, b)
}
func (m *ClusterLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterLeaveRequest.Marshal(b, m, deterministic)
}
func (m *ClusterLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterLeaveRequest.Merge(m, src)
}
func (m *ClusterLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterLeaveRequest.Size(m)
}
func (m *ClusterLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterLeaveRequest proto.InternalMessageInfo

func (m *ClusterLeaveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ClusterInfoResponse struct {
	Cluster              *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterInfoResponse) Reset()         { *m = ClusterInfoResponse{} }
func (m *ClusterInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterInfoResponse) ProtoMessage()    {}
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{8}
}

func (m *ClusterInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfoResponse.Unmarshal(m, b)
}
func (m *ClusterInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfoResponse.Marshal(b, m, deterministic)
}
func (m *ClusterInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfoResponse.Merge(m, src)
}
func (m *ClusterInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterInfoResponse.Size(m)
}
func (m *ClusterInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfoResponse proto.InternalMessageInfo

func (m *ClusterInfoResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type ClusterWatchResponse struct {
	Event                ClusterWatchResponse_Event `protobuf:"varint,1,opt,name=event,proto3,enum=index.ClusterWatchResponse_Event" json:"event,omitempty"`
	Node                 *Node                      `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Cluster              *Cluster                   `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClusterWatchResponse) Reset()         { *m = ClusterWatchResponse{} }
func (m *ClusterWatchResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterWatchResponse) ProtoMessage()    {}
func (*ClusterWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{9}
}

func (m *ClusterWatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterWatchResponse.Unmarshal(m, b)
}
func (m *ClusterWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterWatchResponse.Marshal(b, m, deterministic)
}
func (m *ClusterWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterWatchResponse.Merge(m, src)
}
func (m *ClusterWatchResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterWatchResponse.Size(m)
}
func (m *ClusterWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterWatchResponse proto.InternalMessageInfo

func (m *ClusterWatchResponse) GetEvent() ClusterWatchResponse_Event {
	if m != nil {
		return m.Event
	}
	return ClusterWatchResponse_UNKNOWN
}

func (m *ClusterWatchResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ClusterWatchResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type Document struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *any.Any `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{10}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetFields() *any.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{11}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{12}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type IndexRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *any.Any `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{13}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

func (m *IndexRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexRequest) GetFields() *any.Any {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{14}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BulkIndexRequest struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BulkIndexRequest) Reset()         { *m = BulkIndexRequest{} }
func (m *BulkIndexRequest) String() string { return proto.CompactTextString(m) }
func (*BulkIndexRequest) ProtoMessage()    {}
func (*BulkIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{15}
}

func (m *BulkIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkIndexRequest.Unmarshal(m, b)
}
func (m *BulkIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkIndexRequest.Marshal(b, m, deterministic)
}
func (m *BulkIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkIndexRequest.Merge(m, src)
}
func (m *BulkIndexRequest) XXX_Size() int {
	return xxx_messageInfo_BulkIndexRequest.Size(m)
}
func (m *BulkIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkIndexRequest proto.InternalMessageInfo

func (m *BulkIndexRequest) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type BulkIndexResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkIndexResponse) Reset()         { *m = BulkIndexResponse{} }
func (m *BulkIndexResponse) String() string { return proto.CompactTextString(m) }
func (*BulkIndexResponse) ProtoMessage()    {}
func (*BulkIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{16}
}

func (m *BulkIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkIndexResponse.Unmarshal(m, b)
}
func (m *BulkIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkIndexResponse.Marshal(b, m, deterministic)
}
func (m *BulkIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkIndexResponse.Merge(m, src)
}
func (m *BulkIndexResponse) XXX_Size() int {
	return xxx_messageInfo_BulkIndexResponse.Size(m)
}
func (m *BulkIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkIndexResponse proto.InternalMessageInfo

func (m *BulkIndexResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BulkDeleteRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkDeleteRequest) Reset()         { *m = BulkDeleteRequest{} }
func (m *BulkDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*BulkDeleteRequest) ProtoMessage()    {}
func (*BulkDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{17}
}

func (m *BulkDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkDeleteRequest.Unmarshal(m, b)
}
func (m *BulkDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkDeleteRequest.Marshal(b, m, deterministic)
}
func (m *BulkDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkDeleteRequest.Merge(m, src)
}
func (m *BulkDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_BulkDeleteRequest.Size(m)
}
func (m *BulkDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkDeleteRequest proto.InternalMessageInfo

func (m *BulkDeleteRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type BulkDeleteResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkDeleteResponse) Reset()         { *m = BulkDeleteResponse{} }
func (m *BulkDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*BulkDeleteResponse) ProtoMessage()    {}
func (*BulkDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{18}
}

func (m *BulkDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkDeleteResponse.Unmarshal(m, b)
}
func (m *BulkDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkDeleteResponse.Marshal(b, m, deterministic)
}
func (m *BulkDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkDeleteResponse.Merge(m, src)
}
func (m *BulkDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_BulkDeleteResponse.Size(m)
}
func (m *BulkDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkDeleteResponse proto.InternalMessageInfo

func (m *BulkDeleteResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SearchRequest struct {
	SearchRequest        *any.Any `protobuf:"bytes,1,opt,name=search_request,json=searchRequest,proto3" json:"search_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{19}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearchRequest() *any.Any {
	if m != nil {
		return m.SearchRequest
	}
	return nil
}

type SearchResponse struct {
	SearchResult         *any.Any `protobuf:"bytes,1,opt,name=search_result,json=searchResult,proto3" json:"search_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{20}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetSearchResult() *any.Any {
	if m != nil {
		return m.SearchResult
	}
	return nil
}

type IndexConfig struct {
	IndexMapping         *any.Any `protobuf:"bytes,1,opt,name=index_mapping,json=indexMapping,proto3" json:"index_mapping,omitempty"`
	IndexType            string   `protobuf:"bytes,2,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	IndexStorageType     string   `protobuf:"bytes,3,opt,name=index_storage_type,json=indexStorageType,proto3" json:"index_storage_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexConfig) Reset()         { *m = IndexConfig{} }
func (m *IndexConfig) String() string { return proto.CompactTextString(m) }
func (*IndexConfig) ProtoMessage()    {}
func (*IndexConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{21}
}

func (m *IndexConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexConfig.Unmarshal(m, b)
}
func (m *IndexConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexConfig.Marshal(b, m, deterministic)
}
func (m *IndexConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexConfig.Merge(m, src)
}
func (m *IndexConfig) XXX_Size() int {
	return xxx_messageInfo_IndexConfig.Size(m)
}
func (m *IndexConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IndexConfig proto.InternalMessageInfo

func (m *IndexConfig) GetIndexMapping() *any.Any {
	if m != nil {
		return m.IndexMapping
	}
	return nil
}

func (m *IndexConfig) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

func (m *IndexConfig) GetIndexStorageType() string {
	if m != nil {
		return m.IndexStorageType
	}
	return ""
}

type GetIndexConfigResponse struct {
	IndexConfig          *IndexConfig `protobuf:"bytes,1,opt,name=index_config,json=indexConfig,proto3" json:"index_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetIndexConfigResponse) Reset()         { *m = GetIndexConfigResponse{} }
func (m *GetIndexConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetIndexConfigResponse) ProtoMessage()    {}
func (*GetIndexConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{22}
}

func (m *GetIndexConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexConfigResponse.Unmarshal(m, b)
}
func (m *GetIndexConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetIndexConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexConfigResponse.Merge(m, src)
}
func (m *GetIndexConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetIndexConfigResponse.Size(m)
}
func (m *GetIndexConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexConfigResponse proto.InternalMessageInfo

func (m *GetIndexConfigResponse) GetIndexConfig() *IndexConfig {
	if m != nil {
		return m.IndexConfig
	}
	return nil
}

type GetIndexStatsResponse struct {
	IndexStats           *any.Any `protobuf:"bytes,1,opt,name=index_stats,json=indexStats,proto3" json:"index_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexStatsResponse) Reset()         { *m = GetIndexStatsResponse{} }
func (m *GetIndexStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetIndexStatsResponse) ProtoMessage()    {}
func (*GetIndexStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{23}
}

func (m *GetIndexStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexStatsResponse.Unmarshal(m, b)
}
func (m *GetIndexStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetIndexStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexStatsResponse.Merge(m, src)
}
func (m *GetIndexStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetIndexStatsResponse.Size(m)
}
func (m *GetIndexStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexStatsResponse proto.InternalMessageInfo

func (m *GetIndexStatsResponse) GetIndexStats() *any.Any {
	if m != nil {
		return m.IndexStats
	}
	return nil
}

type Proposal struct {
	Event                Proposal_Event `protobuf:"varint,1,opt,name=event,proto3,enum=index.Proposal_Event" json:"event,omitempty"`
	Node                 *Node          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Document             *Document      `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Id                   string         `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Documents            []*Document    `protobuf:"bytes,5,rep,name=documents,proto3" json:"documents,omitempty"`
	Ids                  []string       `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b2daf652facb3ae, []int{24}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetEvent() Proposal_Event {
	if m != nil {
		return m.Event
	}
	return Proposal_UNKNOWN
}

func (m *Proposal) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Proposal) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *Proposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Proposal) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *Proposal) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterEnum("index.NodeHealthCheckRequest_Probe", NodeHealthCheckRequest_Probe_name, NodeHealthCheckRequest_Probe_value)
	proto.RegisterEnum("index.NodeHealthCheckResponse_State", NodeHealthCheckResponse_State_name, NodeHealthCheckResponse_State_value)
	proto.RegisterEnum("index.Node_State", Node_State_name, Node_State_value)
	proto.RegisterEnum("index.ClusterWatchResponse_Event", ClusterWatchResponse_Event_name, ClusterWatchResponse_Event_value)
	proto.RegisterEnum("index.Proposal_Event", Proposal_Event_name, Proposal_Event_value)
	proto.RegisterType((*NodeHealthCheckRequest)(nil), "index.NodeHealthCheckRequest")
	proto.RegisterType((*NodeHealthCheckResponse)(nil), "index.NodeHealthCheckResponse")
	proto.RegisterType((*Metadata)(nil), "index.Metadata")
	proto.RegisterType((*Node)(nil), "index.Node")
	proto.RegisterType((*Cluster)(nil), "index.Cluster")
	proto.RegisterMapType((map[string]*Node)(nil), "index.Cluster.NodesEntry")
	proto.RegisterType((*NodeInfoResponse)(nil), "index.NodeInfoResponse")
	proto.RegisterType((*ClusterJoinRequest)(nil), "index.ClusterJoinRequest")
	proto.RegisterType((*ClusterLeaveRequest)(nil), "index.ClusterLeaveRequest")
	proto.RegisterType((*ClusterInfoResponse)(nil), "index.ClusterInfoResponse")
	proto.RegisterType((*ClusterWatchResponse)(nil), "index.ClusterWatchResponse")
	proto.RegisterType((*Document)(nil), "index.Document")
	proto.RegisterType((*GetRequest)(nil), "index.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "index.GetResponse")
	proto.RegisterType((*IndexRequest)(nil), "index.IndexRequest")
	proto.RegisterType((*DeleteRequest)(nil), "index.DeleteRequest")
	proto.RegisterType((*BulkIndexRequest)(nil), "index.BulkIndexRequest")
	proto.RegisterType((*BulkIndexResponse)(nil), "index.BulkIndexResponse")
	proto.RegisterType((*BulkDeleteRequest)(nil), "index.BulkDeleteRequest")
	proto.RegisterType((*BulkDeleteResponse)(nil), "index.BulkDeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "index.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "index.SearchResponse")
	proto.RegisterType((*IndexConfig)(nil), "index.IndexConfig")
	proto.RegisterType((*GetIndexConfigResponse)(nil), "index.GetIndexConfigResponse")
	proto.RegisterType((*GetIndexStatsResponse)(nil), "index.GetIndexStatsResponse")
	proto.RegisterType((*Proposal)(nil), "index.Proposal")
}

func init() { proto.RegisterFile("protobuf/index/index.proto", fileDescriptor_7b2daf652facb3ae) }

var fileDescriptor_7b2daf652facb3ae = []byte{
	// 1441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x36, 0x25, 0x51, 0x96, 0x87, 0xfe, 0x61, 0x36, 0xfe, 0x49, 0x18, 0xfb, 0x24, 0xde, 0x73,
	0x72, 0xea, 0x3a, 0xa9, 0x94, 0x3a, 0x08, 0xd2, 0xb8, 0x2d, 0x0a, 0xd9, 0x62, 0x6d, 0xc5, 0x8a,
	0x14, 0x50, 0xb2, 0xd3, 0x14, 0x28, 0x04, 0x4a, 0x5a, 0x4b, 0x84, 0x65, 0x52, 0x15, 0x29, 0xb7,
	0x42, 0xd1, 0x8b, 0xe6, 0x15, 0x8a, 0xa2, 0x0f, 0x52, 0xa0, 0x2f, 0xd0, 0x27, 0x28, 0x7a, 0xdb,
	0xcb, 0x3e, 0x48, 0xb1, 0x7f, 0x14, 0x29, 0x4b, 0x32, 0x72, 0x63, 0x68, 0x67, 0xbe, 0xf9, 0xf6,
	0xdb, 0xe1, 0xce, 0xcc, 0x1a, 0x8c, 0x5e, 0xdf, 0x0b, 0xbc, 0xc6, 0xe0, 0x3c, 0xe7, 0xb8, 0x2d,
	0xf2, 0x3d, 0xff, 0x9b, 0x65, 0x46, 0xa4, 0xb2, 0x85, 0x71, 0xb7, 0xed, 0x79, 0xed, 0x2e, 0xc9,
	0x85, 0x48, 0xdb, 0x1d, 0x72, 0x84, 0x71, 0x6f, 0xdc, 0x45, 0x2e, 0x7b, 0x81, 0x74, 0x6e, 0x0a,
	0xa7, 0xdd, 0x73, 0x72, 0xb6, 0xeb, 0x7a, 0x81, 0x1d, 0x38, 0x9e, 0xeb, 0x73, 0x2f, 0xfe, 0x55,
	0x81, 0xf5, 0xb2, 0xd7, 0x22, 0xc7, 0xc4, 0xee, 0x06, 0x9d, 0xc3, 0x0e, 0x69, 0x5e, 0x58, 0xe4,
	0xdb, 0x01, 0xf1, 0x03, 0xf4, 0x02, 0xd4, 0x5e, 0xdf, 0x6b, 0x90, 0x3b, 0xca, 0x03, 0x65, 0x67,
	0x79, 0xef, 0xbf, 0x59, 0x2e, 0x6a, 0x32, 0x3a, 0xfb, 0x9a, 0x42, 0x2d, 0x1e, 0x81, 0x0f, 0x40,
	0x65, 0x6b, 0xa4, 0xc1, 0xfc, 0x69, 0xf9, 0xa4, 0x5c, 0x79, 0x53, 0xd6, 0xe7, 0xd0, 0x0a, 0x68,
	0xc7, 0x66, 0xbe, 0x54, 0x3b, 0x2e, 0x96, 0xcd, 0x6a, 0x55, 0x57, 0xd0, 0x22, 0x64, 0x4a, 0xc5,
	0x33, 0x93, 0xad, 0x12, 0x68, 0x09, 0x16, 0x2c, 0x33, 0x5f, 0xe0, 0xce, 0x24, 0xfe, 0x5d, 0x81,
	0x8d, 0x6b, 0x7b, 0xf9, 0x3d, 0xcf, 0xf5, 0x09, 0xda, 0x07, 0xd5, 0x0f, 0xec, 0x40, 0x4a, 0xfb,
	0xdf, 0x34, 0x69, 0x1c, 0x9e, 0xad, 0x52, 0xac, 0xc5, 0x43, 0x70, 0x1d, 0x54, 0xb6, 0x8e, 0x6b,
	0xd3, 0x60, 0x9e, 0x6b, 0x7b, 0xab, 0x2b, 0x54, 0xc9, 0x69, 0x59, 0x2e, 0x13, 0x68, 0x01, 0xd4,
	0x3c, 0xd5, 0xa9, 0x27, 0x51, 0x06, 0x52, 0x05, 0x33, 0x5f, 0xd0, 0x53, 0xd4, 0x48, 0xd5, 0xbe,
	0xd5, 0x55, 0x0a, 0x2f, 0x57, 0x6a, 0x75, 0xbe, 0x4c, 0xe3, 0x77, 0x0a, 0x64, 0x5e, 0x91, 0xc0,
	0x6e, 0xd9, 0x81, 0x8d, 0xb6, 0x61, 0xb1, 0xdd, 0xef, 0x35, 0xeb, 0x76, 0xab, 0xd5, 0x27, 0xbe,
	0xcf, 0x04, 0x2f, 0x58, 0x1a, 0xb5, 0xe5, 0xb9, 0x09, 0x3d, 0x81, 0x55, 0x06, 0x69, 0xdb, 0x01,
	0xf9, 0xce, 0x1e, 0x86, 0xd0, 0x04, 0x83, 0x22, 0xea, 0x3b, 0xe2, 0x2e, 0x19, 0xb1, 0x0d, 0x8b,
	0x9d, 0x20, 0xe8, 0x85, 0xc8, 0x24, 0x27, 0xa5, 0x36, 0x01, 0xc1, 0x7f, 0x2b, 0x90, 0xa2, 0xe9,
	0x40, 0xcb, 0x90, 0x70, 0x5a, 0x62, 0xdb, 0x84, 0xd3, 0xa2, 0xb1, 0x0d, 0xc7, 0x6d, 0x8d, 0xed,
	0xa2, 0x51, 0x9b, 0xa4, 0xff, 0x40, 0x66, 0x37, 0xc9, 0xb2, 0x7b, 0x2b, 0x92, 0xdd, 0x58, 0x2a,
	0xd1, 0x23, 0xc8, 0x5c, 0x8a, 0x83, 0xde, 0x49, 0x3d, 0x50, 0x76, 0xb4, 0xbd, 0x15, 0x81, 0x95,
	0xe7, 0xb7, 0x42, 0x00, 0x3e, 0x99, 0x98, 0xf7, 0x45, 0xc8, 0x7c, 0x59, 0x29, 0x95, 0x2a, 0x6f,
	0x4c, 0x8b, 0x27, 0xfe, 0x30, 0x5f, 0x2e, 0x14, 0x0b, 0xf9, 0x9a, 0xa9, 0x27, 0x10, 0x40, 0xba,
	0x64, 0xe6, 0x0b, 0xa6, 0xa5, 0x27, 0x29, 0xb0, 0x7a, 0x7c, 0x5a, 0x2b, 0xd0, 0xb0, 0x14, 0xfe,
	0x49, 0x81, 0xf9, 0xc3, 0xee, 0xc0, 0x0f, 0x48, 0x1f, 0xe5, 0x40, 0x75, 0xbd, 0x16, 0xa1, 0xb9,
	0x4d, 0xee, 0x68, 0x7b, 0x77, 0x85, 0x04, 0xe1, 0x66, 0xb2, 0x7d, 0xd3, 0x0d, 0xfa, 0x43, 0x8b,
	0xe3, 0x0c, 0x13, 0x60, 0x64, 0x44, 0x3a, 0x24, 0x2f, 0xc8, 0x50, 0x64, 0x88, 0xfe, 0x44, 0xdb,
	0xa0, 0x5e, 0xd9, 0xdd, 0x01, 0x61, 0xb9, 0xd1, 0xf6, 0xb4, 0xc8, 0xf9, 0x2d, 0xee, 0xd9, 0x4f,
	0x7c, 0xa2, 0xe0, 0xa7, 0xa0, 0x53, 0x53, 0xd1, 0x3d, 0xf7, 0xc2, 0x8b, 0x79, 0x1f, 0x52, 0x74,
	0x0f, 0xc6, 0x36, 0x16, 0xc9, 0x1c, 0xf8, 0x19, 0x20, 0x21, 0xec, 0xa5, 0xe7, 0xb8, 0xb2, 0xd4,
	0x6e, 0x0c, 0x7b, 0x08, 0xb7, 0x45, 0x58, 0x89, 0xd8, 0x57, 0x44, 0xc6, 0x8d, 0x7d, 0x5c, 0xfc,
	0x45, 0x08, 0x8b, 0xa9, 0xda, 0x81, 0xf9, 0x26, 0x37, 0x8b, 0x1d, 0x96, 0xe3, 0x39, 0xb2, 0xa4,
	0x1b, 0xff, 0xa9, 0xc0, 0xaa, 0x30, 0xbe, 0xb1, 0x83, 0x66, 0x27, 0xa4, 0x78, 0x0e, 0x2a, 0xb9,
	0x22, 0x6e, 0x20, 0x2a, 0x6e, 0x3b, 0x4e, 0x10, 0xc3, 0x66, 0x4d, 0x0a, 0xb4, 0x38, 0x3e, 0x3c,
	0x5a, 0x62, 0xca, 0xd1, 0xa2, 0xe2, 0x92, 0xb3, 0xc5, 0x3d, 0x03, 0x95, 0x51, 0xc7, 0x6f, 0x50,
	0x06, 0x52, 0x2f, 0x2b, 0xc5, 0xb2, 0xae, 0xd0, 0x92, 0x2c, 0x99, 0xf9, 0x33, 0x71, 0x73, 0x4e,
	0x5f, 0xb3, 0x5b, 0x94, 0xc4, 0xc7, 0x90, 0x29, 0x78, 0xcd, 0xc1, 0x25, 0x8d, 0x1c, 0xaf, 0x86,
	0xc7, 0x90, 0x3e, 0x77, 0x48, 0xb7, 0xe5, 0x0b, 0x7d, 0xab, 0x59, 0xde, 0x2d, 0xb3, 0xb2, 0x95,
	0x66, 0xf3, 0xee, 0xd0, 0x12, 0x18, 0xbc, 0x09, 0x70, 0x44, 0x82, 0x69, 0xc9, 0xdf, 0x07, 0x8d,
	0x79, 0x45, 0xc6, 0x1e, 0x41, 0xa6, 0x25, 0xb6, 0x15, 0x59, 0x97, 0xc5, 0x21, 0xd5, 0x58, 0x21,
	0x00, 0x97, 0x60, 0xb1, 0x48, 0x7d, 0x53, 0xb8, 0xdf, 0x53, 0xe7, 0x7d, 0x58, 0x2a, 0x90, 0x2e,
	0x09, 0xa6, 0xde, 0x93, 0x3c, 0xe8, 0x07, 0x83, 0xee, 0x45, 0x6c, 0xcb, 0x8f, 0x60, 0x41, 0xca,
	0x91, 0xa5, 0x74, 0x4d, 0xf0, 0x08, 0x81, 0x3f, 0x84, 0x5b, 0x11, 0x0a, 0x71, 0xe6, 0x55, 0x50,
	0x9b, 0xde, 0x40, 0x1c, 0x58, 0xb5, 0xf8, 0x02, 0x3f, 0xe4, 0xd0, 0xb8, 0x24, 0x1d, 0x92, 0x4e,
	0x8b, 0x6f, 0xb4, 0x60, 0xd1, 0x9f, 0x78, 0x17, 0x50, 0x14, 0x36, 0x93, 0xb2, 0x04, 0x4b, 0x55,
	0x62, 0xf7, 0xe9, 0xa5, 0xe3, 0x74, 0x9f, 0xc2, 0xb2, 0xcf, 0x0c, 0xf5, 0x3e, 0xb7, 0x88, 0x9c,
	0x4f, 0x4e, 0xd4, 0x92, 0x1f, 0x0d, 0xc6, 0x27, 0xb0, 0x2c, 0xd9, 0xc4, 0xae, 0x2f, 0x60, 0x29,
	0xa4, 0xf3, 0x07, 0xdd, 0xd9, 0x6c, 0x8b, 0x92, 0x8d, 0x22, 0xf1, 0x2f, 0x0a, 0x68, 0x2c, 0x2b,
	0x87, 0x9e, 0x7b, 0xee, 0xb4, 0x29, 0x15, 0xcb, 0x62, 0xfd, 0xd2, 0xee, 0xf5, 0x1c, 0xb7, 0x3d,
	0x9b, 0x8a, 0x41, 0x5f, 0x71, 0x24, 0xda, 0x02, 0xe0, 0xa1, 0xc1, 0xb0, 0x47, 0x44, 0xa7, 0x5e,
	0x60, 0x96, 0xda, 0xb0, 0x47, 0xd0, 0x63, 0x40, 0xdc, 0xed, 0x07, 0x5e, 0xdf, 0x6e, 0x13, 0x0e,
	0xe3, 0xc3, 0x40, 0x67, 0x9e, 0x2a, 0x77, 0x50, 0x34, 0xae, 0xc0, 0xfa, 0x11, 0x09, 0x22, 0xca,
	0xc2, 0xc3, 0x3e, 0x03, 0xbe, 0x6d, 0xbd, 0xc9, 0xec, 0x42, 0x20, 0x12, 0x1f, 0x3f, 0x1a, 0xa1,
	0x39, 0xa3, 0x05, 0x2e, 0xc3, 0x9a, 0x24, 0xa4, 0x8d, 0xdd, 0x8f, 0xf0, 0x69, 0x52, 0x97, 0x1d,
	0xf8, 0x33, 0xcf, 0x0b, 0x4e, 0x18, 0x8e, 0xff, 0x48, 0x40, 0xe6, 0x75, 0xdf, 0xeb, 0x79, 0xbe,
	0xdd, 0x45, 0x8f, 0xe2, 0xfd, 0x66, 0x4d, 0x88, 0x91, 0xfe, 0xf7, 0xec, 0x31, 0xd1, 0x5a, 0x4c,
	0xde, 0x50, 0x8b, 0xa2, 0x58, 0x52, 0x61, 0xed, 0xc5, 0x0a, 0x43, 0xbd, 0xa9, 0x30, 0xe4, 0xc5,
	0x4e, 0x8f, 0x2e, 0xf6, 0xc5, 0xc4, 0xbe, 0x45, 0x07, 0x9a, 0x59, 0xab, 0x97, 0x2b, 0x05, 0x53,
	0x57, 0xe8, 0xdb, 0xa8, 0x60, 0x96, 0xcc, 0x9a, 0xc9, 0x0d, 0xec, 0xd1, 0x51, 0x2c, 0x17, 0xcc,
	0xaf, 0xf4, 0x24, 0x6d, 0x66, 0xdc, 0xa7, 0xa7, 0xd0, 0x32, 0xc0, 0xc1, 0x69, 0xe9, 0xa4, 0xce,
	0x7d, 0x2a, 0x8d, 0x63, 0x6b, 0x01, 0x48, 0xef, 0xfd, 0x46, 0x03, 0xa9, 0x38, 0xe4, 0xc2, 0xca,
	0xd8, 0x83, 0x08, 0x6d, 0xcd, 0x7c, 0xc3, 0x19, 0xff, 0x99, 0xfd, 0x8e, 0xc2, 0x9b, 0xef, 0xfe,
	0xfa, 0xe7, 0xe7, 0xc4, 0x3a, 0x5a, 0xcd, 0x5d, 0x7d, 0x9c, 0xa3, 0x89, 0xcd, 0x75, 0x18, 0xaa,
	0xc9, 0xc8, 0x6b, 0x90, 0x91, 0xf3, 0x10, 0xad, 0x5f, 0xfb, 0xda, 0x26, 0x7d, 0x92, 0x1a, 0x1b,
	0x91, 0x1d, 0xa2, 0x23, 0x0a, 0x6f, 0x30, 0xea, 0x5b, 0x68, 0x25, 0xa4, 0xa6, 0x97, 0x67, 0xe0,
	0xa3, 0x03, 0xd0, 0x22, 0x03, 0x13, 0x8d, 0x4d, 0xf7, 0xc8, 0x10, 0x35, 0xa6, 0xec, 0x89, 0xe7,
	0x50, 0x01, 0x16, 0xa3, 0xd3, 0x13, 0x19, 0x71, 0x92, 0xe8, 0x48, 0x9d, 0xc1, 0xf2, 0x4d, 0xa8,
	0x64, 0xe6, 0x11, 0xc7, 0xc8, 0x63, 0xa7, 0x34, 0xd8, 0x29, 0x57, 0x11, 0xa2, 0xa7, 0x14, 0x63,
	0x4d, 0x1e, 0xf4, 0x28, 0x14, 0xc9, 0xa6, 0xe9, 0x54, 0xfe, 0x7b, 0x33, 0x46, 0x2f, 0x9e, 0x7b,
	0xa2, 0xa0, 0x13, 0x48, 0x1e, 0x91, 0x00, 0xc9, 0x67, 0xdb, 0x68, 0x62, 0x19, 0x28, 0x6a, 0x12,
	0x11, 0x5b, 0x4c, 0xd2, 0x06, 0x5a, 0xa3, 0x92, 0xc2, 0x5b, 0x9c, 0xfb, 0xc1, 0x69, 0x7d, 0xbe,
	0xbb, 0xfb, 0x23, 0x3a, 0x93, 0xb7, 0xe9, 0x76, 0xb4, 0x1d, 0xdc, 0x94, 0xac, 0x07, 0x8c, 0xd4,
	0x30, 0x26, 0x93, 0xee, 0x2b, 0xbb, 0xe8, 0x14, 0xd2, 0xbc, 0xd1, 0xa3, 0x55, 0x59, 0x4b, 0xd1,
	0xf1, 0x30, 0x95, 0x59, 0xc8, 0xdd, 0x9d, 0x22, 0xb7, 0x0a, 0x0b, 0xe1, 0x54, 0x42, 0xf2, 0xb2,
	0x8d, 0x8f, 0x3a, 0xe3, 0xce, 0x75, 0x87, 0xc8, 0xc6, 0x6d, 0x46, 0xbf, 0x64, 0x64, 0x28, 0x7d,
	0x63, 0xd0, 0xbd, 0xa0, 0x5a, 0xcf, 0x00, 0x46, 0x83, 0x09, 0x45, 0x83, 0xe3, 0x9a, 0xef, 0x4e,
	0xf0, 0xc4, 0x79, 0x77, 0x63, 0xbc, 0xcf, 0x21, 0xcd, 0xc7, 0x4e, 0x98, 0x83, 0xd8, 0x4c, 0x33,
	0xd6, 0xc6, 0xac, 0xf2, 0x1b, 0xa3, 0x22, 0x2c, 0xc7, 0x5b, 0xf9, 0xd4, 0xcb, 0xb2, 0x35, 0xfa,
	0xe2, 0x13, 0x3a, 0x3f, 0x9e, 0x43, 0x47, 0xb0, 0x14, 0x6b, 0xe2, 0x53, 0x99, 0x36, 0xc7, 0x98,
	0x62, 0x2d, 0x1f, 0xcf, 0xa1, 0xcf, 0x20, 0x53, 0x75, 0xed, 0x9e, 0xdf, 0xf1, 0x82, 0xa9, 0x1c,
	0x53, 0x6b, 0xeb, 0x60, 0xe7, 0xeb, 0xff, 0xb7, 0x9d, 0xa0, 0x33, 0x68, 0x64, 0x9b, 0xde, 0x65,
	0xee, 0xd2, 0xf3, 0x07, 0x17, 0x76, 0xae, 0xd1, 0xb5, 0xfd, 0x20, 0x17, 0xff, 0xcf, 0xb8, 0x91,
	0x66, 0xeb, 0xa7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x90, 0xe3, 0xf5, 0xab, 0x32, 0x0f, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IndexClient is the client API for Index service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexClient interface {
	NodeHealthCheck(ctx context.Context, in *NodeHealthCheckRequest, opts ...grpc.CallOption) (*NodeHealthCheckResponse, error)
	NodeInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NodeInfoResponse, error)
	ClusterJoin(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ClusterLeave(ctx context.Context, in *ClusterLeaveRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ClusterInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ClusterInfoResponse, error)
	ClusterWatch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Index_ClusterWatchClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	BulkIndex(ctx context.Context, in *BulkIndexRequest, opts ...grpc.CallOption) (*BulkIndexResponse, error)
	BulkDelete(ctx context.Context, in *BulkDeleteRequest, opts ...grpc.CallOption) (*BulkDeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetIndexConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetIndexConfigResponse, error)
	GetIndexStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetIndexStatsResponse, error)
	Snapshot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) NodeHealthCheck(ctx context.Context, in *NodeHealthCheckRequest, opts ...grpc.CallOption) (*NodeHealthCheckResponse, error) {
	out := new(NodeHealthCheckResponse)
	err := c.cc.Invoke(ctx, "/index.Index/NodeHealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) NodeInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NodeInfoResponse, error) {
	out := new(NodeInfoResponse)
	err := c.cc.Invoke(ctx, "/index.Index/NodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) ClusterJoin(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/index.Index/ClusterJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) ClusterLeave(ctx context.Context, in *ClusterLeaveRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/index.Index/ClusterLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) ClusterInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	out := new(ClusterInfoResponse)
	err := c.cc.Invoke(ctx, "/index.Index/ClusterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) ClusterWatch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Index_ClusterWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Index_serviceDesc.Streams[0], "/index.Index/ClusterWatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &indexClusterWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Index_ClusterWatchClient interface {
	Recv() (*ClusterWatchResponse, error)
	grpc.ClientStream
}

type indexClusterWatchClient struct {
	grpc.ClientStream
}

func (x *indexClusterWatchClient) Recv() (*ClusterWatchResponse, error) {
	m := new(ClusterWatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *indexClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/index.Index/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/index.Index/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/index.Index/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) BulkIndex(ctx context.Context, in *BulkIndexRequest, opts ...grpc.CallOption) (*BulkIndexResponse, error) {
	out := new(BulkIndexResponse)
	err := c.cc.Invoke(ctx, "/index.Index/BulkIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) BulkDelete(ctx context.Context, in *BulkDeleteRequest, opts ...grpc.CallOption) (*BulkDeleteResponse, error) {
	out := new(BulkDeleteResponse)
	err := c.cc.Invoke(ctx, "/index.Index/BulkDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/index.Index/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexConfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetIndexConfigResponse, error) {
	out := new(GetIndexConfigResponse)
	err := c.cc.Invoke(ctx, "/index.Index/GetIndexConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetIndexStats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetIndexStatsResponse, error) {
	out := new(GetIndexStatsResponse)
	err := c.cc.Invoke(ctx, "/index.Index/GetIndexStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Snapshot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/index.Index/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServer is the server API for Index service.
type IndexServer interface {
	NodeHealthCheck(context.Context, *NodeHealthCheckRequest) (*NodeHealthCheckResponse, error)
	NodeInfo(context.Context, *empty.Empty) (*NodeInfoResponse, error)
	ClusterJoin(context.Context, *ClusterJoinRequest) (*empty.Empty, error)
	ClusterLeave(context.Context, *ClusterLeaveRequest) (*empty.Empty, error)
	ClusterInfo(context.Context, *empty.Empty) (*ClusterInfoResponse, error)
	ClusterWatch(*empty.Empty, Index_ClusterWatchServer) error
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Index(context.Context, *IndexRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	BulkIndex(context.Context, *BulkIndexRequest) (*BulkIndexResponse, error)
	BulkDelete(context.Context, *BulkDeleteRequest) (*BulkDeleteResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetIndexConfig(context.Context, *empty.Empty) (*GetIndexConfigResponse, error)
	GetIndexStats(context.Context, *empty.Empty) (*GetIndexStatsResponse, error)
	Snapshot(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedIndexServer can be embedded to have forward compatible implementations.
type UnimplementedIndexServer struct {
}

func (*UnimplementedIndexServer) NodeHealthCheck(ctx context.Context, req *NodeHealthCheckRequest) (*NodeHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeHealthCheck not implemented")
}
func (*UnimplementedIndexServer) NodeInfo(ctx context.Context, req *empty.Empty) (*NodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeInfo not implemented")
}
func (*UnimplementedIndexServer) ClusterJoin(ctx context.Context, req *ClusterJoinRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterJoin not implemented")
}
func (*UnimplementedIndexServer) ClusterLeave(ctx context.Context, req *ClusterLeaveRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterLeave not implemented")
}
func (*UnimplementedIndexServer) ClusterInfo(ctx context.Context, req *empty.Empty) (*ClusterInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterInfo not implemented")
}
func (*UnimplementedIndexServer) ClusterWatch(req *empty.Empty, srv Index_ClusterWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method ClusterWatch not implemented")
}
func (*UnimplementedIndexServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedIndexServer) Index(ctx context.Context, req *IndexRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (*UnimplementedIndexServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedIndexServer) BulkIndex(ctx context.Context, req *BulkIndexRequest) (*BulkIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkIndex not implemented")
}
func (*UnimplementedIndexServer) BulkDelete(ctx context.Context, req *BulkDeleteRequest) (*BulkDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkDelete not implemented")
}
func (*UnimplementedIndexServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedIndexServer) GetIndexConfig(ctx context.Context, req *empty.Empty) (*GetIndexConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexConfig not implemented")
}
func (*UnimplementedIndexServer) GetIndexStats(ctx context.Context, req *empty.Empty) (*GetIndexStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (*UnimplementedIndexServer) Snapshot(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_NodeHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).NodeHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/NodeHealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).NodeHealthCheck(ctx, req.(*NodeHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/NodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).NodeInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_ClusterJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).ClusterJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/ClusterJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).ClusterJoin(ctx, req.(*ClusterJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_ClusterLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).ClusterLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/ClusterLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).ClusterLeave(ctx, req.(*ClusterLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_ClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).ClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/ClusterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).ClusterInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_ClusterWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IndexServer).ClusterWatch(m, &indexClusterWatchServer{stream})
}

type Index_ClusterWatchServer interface {
	Send(*ClusterWatchResponse) error
	grpc.ServerStream
}

type indexClusterWatchServer struct {
	grpc.ServerStream
}

func (x *indexClusterWatchServer) Send(m *ClusterWatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Index_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_BulkIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).BulkIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/BulkIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).BulkIndex(ctx, req.(*BulkIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_BulkDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).BulkDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/BulkDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).BulkDelete(ctx, req.(*BulkDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/GetIndexConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexConfig(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/GetIndexStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetIndexStats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Snapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Snapshot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "index.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeHealthCheck",
			Handler:    _Index_NodeHealthCheck_Handler,
		},
		{
			MethodName: "NodeInfo",
			Handler:    _Index_NodeInfo_Handler,
		},
		{
			MethodName: "ClusterJoin",
			Handler:    _Index_ClusterJoin_Handler,
		},
		{
			MethodName: "ClusterLeave",
			Handler:    _Index_ClusterLeave_Handler,
		},
		{
			MethodName: "ClusterInfo",
			Handler:    _Index_ClusterInfo_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Index_Get_Handler,
		},
		{
			MethodName: "Index",
			Handler:    _Index_Index_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Index_Delete_Handler,
		},
		{
			MethodName: "BulkIndex",
			Handler:    _Index_BulkIndex_Handler,
		},
		{
			MethodName: "BulkDelete",
			Handler:    _Index_BulkDelete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Index_Search_Handler,
		},
		{
			MethodName: "GetIndexConfig",
			Handler:    _Index_GetIndexConfig_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _Index_GetIndexStats_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Index_Snapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClusterWatch",
			Handler:       _Index_ClusterWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/index/index.proto",
}
